### ISSUE TITLE
How to make it work when importing from CDN directly to the HTML page?

### ISSUE THREAD

**Issue by MyTestPerson** [vinz3872/vuejs-tree#40]
This works well using NPM and does not work when imported from a CDN. How to make it work when importing from CDN directly to the HTML page?

**Comment by WpSlt** [comment]
With the same problem, i got:
[Vue warn]: Component is missing template or render function

using:
<script src="https://cdn.jsdelivr.net/npm/vuejs-tree@3.0.1/dist/vuejs-tree.umd.js" ></script>
    <div id="test">
		<Tree id="my-tree-id" ref="my-tree-ref" :nodes="treeDisplayData"></Tree>
    </div>

const test= Vue.createApp({
	data: function () {
            return {
		  treeDisplayData: [...]
});
test.component("Tree", window['vuejs-tree']);
const testEl = test.mount('#test')

**Comment by vinz3872** [comment]
Hello, you need to add `.default` in the component line to make it work
`test.component("Tree", window['vuejs-tree'].default);`

Maybe it's because i use a "export default tree" for the component, i'm not really sure
here's a stackoverflow post that might interest you [template-or-render-function-not-defined-in-vue](https://stackoverflow.com/questions/48849554/failed-to-mount-component-template-or-render-function-not-defined-in-vue-des)
